apiVersion: v1
kind: Service
metadata:
  name: python-on-kube-service
spec:
  selector:
    app: python-on-kube
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-on-kube
  labels:
    app: python-on-kube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-on-kube
  template:
    metadata:
      labels:
        app: python-on-kube
    spec:
      containers:
      - name: python-on-kube
        image: jonahmary17/python-on-kube:latest
        ports:
        - containerPort: 5000